-- generated by Wicked's loot machine (python)
stepotest_01_00000000000000000 = {
minimumLevel = 0,
maximumLevel = 0,
customObjectName = "",
directObjectTemplate = "object/tangible/cards/stepotest_01_00000000000000000.iff",
craftingValues = { },
customizationStringNames = { },
customizationValues = { }
}
addLootItemTemplate("stepotest_01_00000000000000000", stepotest_01_00000000000000000)
