-- generated by Wicked's loot machine (python)
-- string name is in cards_n: pelgo_red_8
-- string description is in cards_d: pelgo_red_8
-- layout: playing card
object_tangible_cards_pelgo_red_8_000000000000000000 = object_tangible_cards_shared_pelgo_red_8_000000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_pelgo_red_8_000000000000000000, "object/tangible/cards/pelgo_red_8_000000000000000000.iff")
