-- generated by Wicked's loot machine (python)
-- string name is in cards_n: pelgo_green_k
-- string description is in cards_d: pelgo_green_k
-- layout: playing card
object_tangible_cards_pelgo_green_k_0000000000000000 = object_tangible_cards_shared_pelgo_green_k_0000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_pelgo_green_k_0000000000000000, "object/tangible/cards/pelgo_green_k_0000000000000000.iff")
