-- generated by Wicked's loot machine (python)
-- string name is in cards_n: pelgo_pink_4
-- string description is in cards_d: pelgo_pink_4
-- layout: playing card
object_tangible_cards_pelgo_pink_4_00000000000000000 = object_tangible_cards_shared_pelgo_pink_4_00000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_pelgo_pink_4_00000000000000000, "object/tangible/cards/pelgo_pink_4_00000000000000000.iff")
