-- generated by Wicked's loot machine (python)
-- string name is in cards_n: pelgo_blue_a
-- string description is in cards_d: pelgo_blue_a
-- layout: playing card
object_tangible_cards_pelgo_blue_a_00000000000000000 = object_tangible_cards_shared_pelgo_blue_a_00000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_pelgo_blue_a_00000000000000000, "object/tangible/cards/pelgo_blue_a_00000000000000000.iff")
