-- generated by Wicked's loot machine (python)
-- string name is in cards_n: pelgo_aqua_k
-- string description is in cards_d: pelgo_aqua_k
-- layout: playing card
object_tangible_cards_pelgo_aqua_k_00000000000000000 = object_tangible_cards_shared_pelgo_aqua_k_00000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_pelgo_aqua_k_00000000000000000, "object/tangible/cards/pelgo_aqua_k_00000000000000000.iff")
