-- generated by Wicked's loot machine (python)
pelgo_yellow_j_000000000000000 = {
minimumLevel = 0,
maximumLevel = 0,
customObjectName = "",
directObjectTemplate = "object/tangible/cards/pelgo_yellow_j_000000000000000.iff",
craftingValues = { },
customizationStringNames = { },
customizationValues = { }
}
addLootItemTemplate("pelgo_yellow_j_000000000000000", pelgo_yellow_j_000000000000000)
