-- generated by Wicked's loot machine (python)
-- string name is in cards_n: stepotest_01
-- string description is in cards_d: stepotest_01
-- layout: playing card
object_tangible_cards_stepotest_01_00000000000000000 = object_tangible_cards_shared_stepotest_01_00000000000000000:new {}
ObjectTemplates:addTemplate(object_tangible_cards_stepotest_01_00000000000000000, "object/tangible/cards/stepotest_01_00000000000000000.iff")
